version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      PASSWORD: secret
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://localhost:29092
      KAFKA_SSL_KEYSTORE_FILENAME: '/certs/kafka.zookeeper.keystore.jks'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: '/certs/ssl.cert'
      KAFKA_SSL_KEY_CREDENTIALS: '/certs/ssl.cert'
      KAFKA_SSL_TRUSTSTORE_FILENAME: '/certs/kafka.zookeeper.truststore.jks'
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_TRUSTSTOREE_TYPE: JKS
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "metrics-topic:1:1"
    volumes:
      - ./certs/:/etc/kafka/secrets/certs
